name = "service-marketplace"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[env.production]
routes = [
  { pattern = "your-domain.pages.dev/*", zone_name = "your-domain.pages.dev" }
]

[env.production.vars]
ENVIRONMENT = "production"
